### ISSUE TITLE
Contributor's Guide

### ISSUE THREAD

**Issue by matejpavlovic** [hyperledger-labs/mirbft#16]
We need to formulate a Contributor's Guide document that describes the workflow used for adding contributions.
The [FPC Git flows](https://docs.google.com/document/d/1sR7YV3pSYN3NEFiW-2fUqtpsJeJrpC0EWUVtEm0Blcg/edit) can serve as a great starting point.

**Comment by mbrandenburger** [comment]
Let me try to provide an initial version for this.
