### ISSUE TITLE
Crash recovery implementation

### ISSUE THREAD

**Issue by harrymknight** [hyperledger-labs/mirbft#47]
The state machine crashes upon restarting due a to a nil pointer dereference deeming the WAL redundant. This can be reproduced by starting a node, stopping it, and then restarting it.

By tracing the state machine events it is found that the origin of the crash is `et.myNewEpoch`, which is uninitialised during reinitialisation and is broadcast until the target epoch reaches normal operation. This bug is therefore resolved by only broadcasting `et.myNewEpoch` when it is not unintialised.

After doing so however, the target epoch stops progressing.This is because the restarted node does not have the state which it should transfer to following reinitialisation. If this node obtains the necessary state and then catches up to it then crash recovery has been implemented.

A possible implementation of crash recovery is as follows:
- After restarting a node will check the value of `et.myNewEpoch`. As it is uninitialised the node knows it has to state transfer.
- The state which the node should transfer to should be that of the next epoch (relative to the current epoch of the well-behaving nodes).
- Therefore the target epoch of the node enters state `etPending` (and not `etPrepending` as it lacks an epoch change to propose), where it will remain until the current epoch ends.
- In this state it will wait to receive the new epoch from the primary which upon receiving it will validate using the epoch change messages it has also received from the other nodes. 
- If the node is the primary then the current epoch will ungracefully end (due to suspicions raised by the well behaving nodes). A new primary will then be selected by round-robin and this new primary will send the node the new epoch.
- In either case after receiving the new epoch, the node will undergo state transfer following the start of the new epoch (as its highest committed sequence number will be below the starting sequence number of the new epoch) using the state within the new epoch.
- The node will then either have the same state as the other well-behaving nodes, or be able to initiate further state transfers if its state is still behind.

**Comment by matejpavlovic** [comment]
This issue is legitimate, but concerns legacy code (on the legacy branch) and should not be expected to be fixed.
